
services:
  minio1:
    image: minio/minio
    container_name: stor-minio1
    volumes:
      - data1-1:/datapic
      - data1-2:/data2
    ports:
      - "9020:9000"  # Map host port 9020 to container port 9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data1  # Use the mounted volume directly
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9020/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1-1:
  data1-2:
